import {
  Home,
  Bed,
  Apple,
  UserRound,
  PanelsLeftBottom,
  BookOpenTextIcon,
  Logs,
  KeySquare,
  PencilLine,
} from "lucide-react";

const options = [
  {
    name: "Inicio",
    id: 1,
    href: null,
    icon: null,
    isClickable: false,
    isAction: false,
    isEditable: false,
    submenu: [
      {
        name: "Dashboard",
        id: 1,
        href: "/",
        icon: PanelsLeftBottom,
        isClickable: false,
        isAction: false,
        isEditable: false,
        submenu: null,
      },
      {
        name: "Clientes",
        id: 2,
        href: "/clients",
        icon: UserRound,
        isClickable: true,
        isAction: false,
        isEditable: false,
        submenu: null,
      },
      {
        name: "Facturas",
        id: 3,
        href: "/facturas",
        icon: BookOpenTextIcon,
        isClickable: true,
        isAction: false,
        isEditable: false,
        submenu: null,
      },
    ],
  },
  {
    name: "Gestión",
    id: 2,
    href: null,
    icon: null,
    isClickable: false,
    isAction: false,
    isEditable: false,
    submenu: [
      {
        name: "Almacén",
        id: 1,
        href: "/warehouse",
        icon: Home,
        isClickable: true,
        isAction: false,
        isEditable: false,
        submenu: null,
      },
      {
        name: "Habitaciones",
        id: 2,
        href: "/rooms",
        icon: Bed,
        isClickable: true,
        isAction: false,
        isEditable: false,
        submenu: null,
      },
      {
        name: "Administración",
        id: 3,
        href: "/admin",
        icon: KeySquare,
        isClickable: true,
        isAction: false,
        isEditable: false,
        submenu: null,
      },
    ],
  },
  {
    name: "Nomencladores",
    id: 3,
    href: null,
    icon: null,
    isClickable: false,
    isAction: false,
    isEditable: false,
    submenu: [
      {
        name: "Productos",
        id: 1,
        href: "/products",
        icon: Apple,
        isClickable: true,
        isAction: false,
        isEditable: false,
        submenu: null,
      },
    ],
  },
  {
    name: "Información",
    id: 4,
    href: null,
    icon: null,
    isClickable: false,
    isAction: false,
    isEditable: false,
    submenu: [
      {
        name: "Observaciones",
        id: 2,
        href: "/notes",
        icon: PencilLine,
        isClickable: true,
        isAction: false,
        isEditable: false,
        submenu: null,
      },
    ],
  },
];

export default options;
